/**
 * Seed entry point. Screens import { seedLibrary, seedQuestions, ... } from
 * '@/seed' and never touch the underlying files.
 *
 * Now backed by the REAL ETL output (library_v1 / state_plans_v1 /
 * scoping_questions_v1), generated by `npm run etl` from WLS_Audit_Coach_OSHA.xlsx:
 * 286 federal + 88 state = 374 items, 15 scoping questions. Placeholder retired.
 */
import type { LibraryItem } from '@/db/types';
import type { ScopingQuestion } from '@/domain/applicability';
import libraryJson from './library_v1.json';
import statePlansJson from './state_plans_v1.json';
import scopingJson from './scoping_questions_v1.json';

export const IS_PLACEHOLDER = false;
export const LIBRARY_VERSION_ID = 'library-v1';

const federalItems = libraryJson.items as LibraryItem[];
const stateItems = statePlansJson.items as LibraryItem[];

/** Federal items (state=null) + ALL state items; createAudit filters by plan. */
export const seedLibrary: LibraryItem[] = [...federalItems, ...stateItems];

/** The 22 available state plans (full display names). */
export const statePlans: string[] = statePlansJson.plans as string[];

export const seedQuestions: ScopingQuestion[] = (scopingJson.questions as Array<{
  key: string;
  question: string;
  activates: string[];
  applies_on: 'Yes' | 'No';
}>).map((q) => ({
  key: q.key,
  question: q.question,
  activates: q.activates,
  applies_on: q.applies_on,
}));

// Section display names: federal section map + one entry per state plan
// (state items carry section_code = the 2-letter state code, e.g. "CA").
export const sectionNames: Record<string, string> = { ...(libraryJson.sections as Record<string, string>) };
for (const it of stateItems) {
  if (it.state) sectionNames[it.section_code] ??= it.state;
}

/** Ordered section codes as they appear in the library (stable display order). */
export const sectionOrder: string[] = seedLibrary.reduce<string[]>((acc, it) => {
  if (!acc.includes(it.section_code)) acc.push(it.section_code);
  return acc;
}, []);

const byCode = new Map(seedLibrary.map((li) => [li.item_code, li]));
export function libraryItem(code: string): LibraryItem | undefined {
  return byCode.get(code);
}
export const libraryByCode: Map<string, LibraryItem> = byCode;
