/**
 * Generate supabase/seed/library_v1.sql — loads the ETL library into the cloud
 * `items` / `scoping_questions` tables so the backend mirrors the on-device seed.
 *
 *   npm run gen:seed
 *
 * Run the emitted SQL in the Supabase SQL editor (it runs as the table owner, so
 * it bypasses RLS). Idempotent: re-running upserts by primary key.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const SEED = resolve(ROOT, 'src/seed');
const OUT_DIR = resolve(ROOT, 'supabase/seed');
const LIBRARY_VERSION_ID = 'library-v1';

interface LibItem {
  item_code: string;
  section_code: string;
  subsection: string | null;
  requirement: string;
  evidence_protocol: string;
  max_points: number;
  citation: string;
  sif_potential: boolean;
  content_hash: string;
  state: string | null;
}
interface Question {
  key: string;
  question: string;
  activates: string[];
  applies_on: 'Yes' | 'No';
}

const lib = JSON.parse(readFileSync(resolve(SEED, 'library_v1.json'), 'utf8')) as { items: LibItem[] };
const state = JSON.parse(readFileSync(resolve(SEED, 'state_plans_v1.json'), 'utf8')) as { items: LibItem[] };
const scoping = JSON.parse(readFileSync(resolve(SEED, 'scoping_questions_v1.json'), 'utf8')) as { questions: Question[] };

const items = [...lib.items, ...state.items];

/** SQL string literal with quote-doubling. */
function q(v: string | null): string {
  if (v == null) return 'null';
  return `'${v.replace(/'/g, "''")}'`;
}
function arr(vals: string[]): string {
  return vals.length ? `array[${vals.map(q).join(',')}]::text[]` : `'{}'::text[]`;
}

const lines: string[] = [];
lines.push('-- Cloud library seed — generated by scripts/gen_cloud_seed.ts. Do not edit by hand.');
lines.push('-- Run in the Supabase SQL editor (bypasses RLS as table owner). Idempotent.');
lines.push('');
lines.push(`insert into orgs (id, slug, name) values ('wls','wls','Workplace Learning System') on conflict (id) do nothing;`);
lines.push(`insert into item_library_versions (id, notes) values ('${LIBRARY_VERSION_ID}','ETL-generated library') on conflict (id) do nothing;`);
lines.push('');

lines.push('insert into items (library_version_id, item_code, section_code, subsection, requirement, evidence_protocol, max_points, citation, sif_potential, content_hash, state) values');
lines.push(
  items
    .map(
      (it) =>
        `  ('${LIBRARY_VERSION_ID}',${q(it.item_code)},${q(it.section_code)},${q(it.subsection)},${q(it.requirement)},${q(it.evidence_protocol)},${it.max_points},${q(it.citation)},${it.sif_potential},${q(it.content_hash)},${q(it.state)})`,
    )
    .join(',\n'),
);
lines.push(
  'on conflict (library_version_id, item_code) do update set requirement = excluded.requirement, evidence_protocol = excluded.evidence_protocol, max_points = excluded.max_points, citation = excluded.citation, subsection = excluded.subsection, content_hash = excluded.content_hash, state = excluded.state;',
);
lines.push('');

lines.push('insert into scoping_questions (library_version_id, key, question, activates, applies_on) values');
lines.push(
  scoping.questions
    .map((s) => `  ('${LIBRARY_VERSION_ID}',${q(s.key)},${q(s.question)},${arr(s.activates)},${q(s.applies_on)})`)
    .join(',\n'),
);
lines.push('on conflict (library_version_id, key) do update set question = excluded.question, activates = excluded.activates, applies_on = excluded.applies_on;');
lines.push('');

if (!existsSync(OUT_DIR)) mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(resolve(OUT_DIR, 'library_v1.sql'), lines.join('\n') + '\n');
console.log(`✓ wrote supabase/seed/library_v1.sql — ${items.length} items, ${scoping.questions.length} scoping questions`);
